version: "3.5"

services:
    api01: &api
        image: frankapp
        build: .
        depends_on:
            db:
                condition: service_healthy
        environment:
            - CADDY_DEBUG=debug
            - DEBUG=debug
            - FRANKENPHP_CONFIG=worker /srv/public/index.php
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "160MB"

    api02:
        <<: *api

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: "30MB"

    db:
        image: postgres
        hostname: db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: rinhadb
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
        command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
        # network_mode: host
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        deploy:
            resources:
                limits:
                    cpus: "0.4"
                    memory: "200MB"
