version: "3.5"

services:
    app:
        image: frankapp
        build: .
        ports:
            - 8080:80
            - 8443:443
        environment:
            - CADDY_DEBUG=debug
            - DEBUG=debug
            - FRANKENPHP_CONFIG=worker /srv/public/index.php
        volumes:
            - ./:/srv
            - ./Caddyfile:/etc/caddy/Caddyfile

    db:
        image: postgres
        hostname: db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: rinhadb
        ports:
            - "5432:5432"
        # volumes:
        #     - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
        # command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
        # network_mode: host
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
